# based on:
# https://www.getzola.org/documentation/deployment/netlify/

[build]
publish = "public"
command = "zola build"

[build.environment]
ZOLA_VERSION = "0.14.0"

[context.deploy-preview]
command = "zola build --base-url $DEPLOY_PRIME_URL"
